version: 2 #circleci yml api version
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2025.04
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=true
    steps:
      - checkout
      - restore_cache:
          # bump the cache version number if you want to wipe the gradle cache
          key: v1-gradle-dependencies-cache
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-dependencies-cache

      - run:
          name: Run Tests n8-core
          command: ./gradlew n8-core:test
      - store_artifacts:
          path: n8-core/build/reports
      - store_test_results:
          path: n8-core/build/test-results
